apiVersion: asdb.aerospike.com/v1
kind: AerospikeCluster
metadata:
  name: {{ template "aerospike-cluster.commonName" . }}
  namespace: {{ .Release.Namespace }}
  # finalizer needed to handle pvc deletion when AerospikeCluster is deleted.
  finalizers:
    - asdb.aerospike.com/storage-finalizer
  labels:
    app: {{ template "aerospike-cluster.commonName" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    # needed after first ako-3.3.0 reconciliation to allow scale-up
    aerospike.com/api-version: v1
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

spec:
  # Aerospike cluster size
  size: {{ .Values.replicas }}

  # Control PodDisruptionBudget creation for the Aerospike cluster.
  disablePDB: {{ .Values.disablePDB | default false}}
  maxUnavailable: {{ if not .Values.disablePDB }}{{ .Values.maxUnavailable }}{{end}}

  # Aerospike server docker image
  image: {{ .Values.image.repository | default "aerospike/aerospike-server-enterprise" }}:{{ .Values.image.tag | default "8.1.0.0" }}

  ## maxUnavailable defines percentage/number of pods that can be allowed to go down or unavailable
  ## before application disruption.
  maxUnavailable: {{ .Values.maxUnavailable }}

  ## Disable the PodDisruptionBudget creation for the Aerospike cluster.
  disablePDB: {{ .Values.disablePDB }}

  # Aerospike access control configuration
  {{- with .Values.aerospikeAccessControl }}
  aerospikeAccessControl: {{- toYaml . | nindent 4 }}
  {{- end }}

  # Aerospike configuration
  {{- with .Values.aerospikeConfig }}
  aerospikeConfig: {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if and .Values.devMode (not .Values.aerospikeConfig) }}
  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secrets/features.conf

    network:
      service:
        port: 3000
      fabric:
        port: 3001
      heartbeat:
        port: 3002

    namespaces:
      - name: test
        replication-factor: 2
        storage-engine:
          type: memory
          data-size: 1073741824 # 1GiB

  {{- end }}

  ## enableDynamicConfigUpdate enables dynamic config update flow of the operator.
  enableDynamicConfigUpdate: {{ .Values.enableDynamicConfigUpdate }}

  # Aerospike network policy
  {{- with .Values.aerospikeNetworkPolicy }}
  aerospikeNetworkPolicy: {{- toYaml . | nindent 4 }}
  {{- end }}

  # Aerospike pod spec
  podSpec:
    aerospikeContainer:
      {{- with .Values.podSpec.aerospikeContainer }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    aerospikeInitContainer:
      image: {{ .Values.podSpec.aerospikeInitContainer.image }}
      imageRegistry: {{ .Values.podSpec.aerospikeInitContainer.imageRegistry }}
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: aerospike.com/cr
                operator: In
                values:
                - {{ .Values.commonName }}
            topologyKey: {{ .Values.podSpec.affinity.podAntiAffinity.topologyKey }}
          weight: 100
    hostNetwork: {{ .Values.podSpec.hostNetwork }}
    metadata:
      labels:
        {{- if .Values.podSpec.metadata }}
        {{- if .Values.podSpec.metadata.labels}}
        {{- range $key, $val := .Values.podSpec.metadata.labels }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
        {{- end }}
        {{- end}}
    sidecars:
    - args:
      - |
        export METRIC_LABELS="pod=\"$MY_POD_NAME\", host_ip=\"$MY_HOST_IP\""
        /docker-entrypoint.sh aerospike-prometheus-exporter --config /etc/aerospike-prometheus-exporter/ape.toml;
      command:
      - /bin/sh
      - -c
      env:
      - name: AGENT_LOG_LEVEL
        value: debug
      - name: AS_HOST
        value: localhost
      - name: AS_PORT
        value: "4333"
      - name: AS_ROOT_CA
        value: /etc/aerospike/ca/root_ca.pem
      - name: AS_NODE_TLS_NAME
        valueFrom:
          configMapKeyRef:
            key: tls-name
            name: prometheus-exporter-configmap
      - name: AS_AUTH_USER
        value: {{ .Values.podSpec.sidecars.aerospikePrometheusExporter.user }}
      - name: AS_AUTH_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: {{ .Values.podSpec.sidecars.aerospikePrometheusExporter.passwordSecret }}
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      image: {{ .Values.podSpec.sidecars.aerospikePrometheusExporter.image }}
      name: aerospike-prometheus-exporter
      ports:
      - containerPort: {{ .Values.podSpec.sidecars.aerospikePrometheusExporter.port }}
        {{- if .Values.podSpec.hostNetwork }}
        hostPort: {{ .Values.podSpec.sidecars.aerospikePrometheusExporter.port }}
        {{- end}}
        name: exporter
      resources:
        limits:
          cpu: 100m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 200Mi
    tolerations:
    {{- if .Values.podSpec.tolerations }}
    {{- .Values.podSpec.tolerations | toYaml | nindent 4 }}
    {{- end }}

  # Rack configuration
  {{- with .Values.rackConfig }}
  rackConfig: {{- toYaml . | nindent 4 }}
  {{- end }}

  # Storage configuration
  {{- with .Values.storage }}
  storage: {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if and .Values.devMode (not .Values.storage) }}
  storage:
    volumes:
    - name: aerospike-config-secret
      source:
        secret:
          secretName: aerospike-secret
      aerospike:
        path: /etc/aerospike/secrets
  {{- end }}

  # Validation policy
  {{- with .Values.validationPolicy }}
  validationPolicy: {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if and .Values.devMode (not .Values.validationPolicy) }}
  validationPolicy:
    skipWorkDirValidate: true
    skipXdrDlogFileValidate: true
  {{- end }}

  # operatorClientCert defines certificates to connect to Aerospike
  {{- with .Values.operatorClientCert }}
  operatorClientCert: {{- toYaml . | nindent 4 }}
  {{- end }}

  # seedsFinderServices defines service (e.g. loadbalancer) to connect to Aerospike
  {{- with .Values.seedsFinderServices }}
  seedsFinderServices: {{- toYaml . | nindent 4 }}
  {{- end }}

  ## headlessService defines additional configuration parameters for the headless service created to discover Aerospike Cluster nodes
  {{- with .Values.headlessService }}
  headlessService: {{- toYaml . | nindent 4 }}
  {{- end }}

  ## podService defines additional configuration parameters for the pod service created to expose the Aerospike Cluster nodes outside the Kubernetes cluster.
  {{- with .Values.podService }}
  podService: {{- toYaml . | nindent 4 }}
  {{- end }}

  ## rosterNodeBlockList is a list of blocked nodeIDs from roster in a strong-consistency setup
  {{- with .Values.rosterNodeBlockList }}
  rosterNodeBlockList: {{- toYaml . | nindent 4 }}
  {{- end }}

  ## k8sNodeBlockList is a list of Kubernetes nodes which are not used for Aerospike pods.
  {{- with .Values.k8sNodeBlockList }}
  k8sNodeBlockList: {{- toYaml . | nindent 4 }}
  {{- end }}

  ## operations is a list of on-demand operations to be performed on the Aerospike cluster.
  {{- with .Values.operations }}
  operations: {{- toYaml . | nindent 4 }}
  {{- end }}

  ## Pause reconciliation of the cluster
  paused: {{ .Values.paused }}
